kafka-producer:
  delayMs: 1000
  topic: string-values
  properties:
    "[bootstrap.servers]": localhost:9092
    "[key.serializer]": org.apache.kafka.common.serialization.LongSerializer
    "[value.serializer]": org.apache.kafka.common.serialization.StringSerializer
    "[batch.size]": 16384
    "[linger.ms]": 0
    "[enable.idempotence]": false
